# Generated by Django 4.2.7 on 2025-10-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Full path to the file', max_length=500)),
                ('file_name', models.CharField(help_text='File name with extension', max_length=255)),
                ('file_format', models.CharField(help_text='File extension/format', max_length=50)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('sample_rate', models.IntegerField(blank=True, help_text='Sample rate in Hz (audio/video)', null=True)),
                ('bit_depth', models.IntegerField(blank=True, help_text='Bit depth (audio/video)', null=True)),
                ('codec', models.CharField(blank=True, help_text='Codec used for encoding', max_length=50, null=True)),
                ('media_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')], help_text='Type of media file', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'db_table': 'catalog_file',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['media_type'], name='catalog_fil_media_t_145ff2_idx'), models.Index(fields=['file_format'], name='catalog_fil_file_fo_fc5b34_idx'), models.Index(fields=['-created_at'], name='catalog_fil_created_77bde2_idx')],
            },
        ),
    ]
