# Generated by Django 4.2.7 on 2025-10-05 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_path', models.CharField(help_text='Input directory path', max_length=500)),
                ('output_path', models.CharField(help_text='Output directory path', max_length=500)),
                ('is_watched', models.BooleanField(default=False, help_text='Whether this directory is actively monitored')),
            ],
            options={
                'verbose_name': 'Directory Mapping',
                'verbose_name_plural': 'Directory Mappings',
                'db_table': 'catalog_directory_mapping',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique schema name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of schema purpose', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only one schema can be active at a time')),
                ('xml_source', models.TextField(blank=True, help_text='Original XML content for export (NFR14)', null=True)),
                ('source_type', models.CharField(choices=[('web', 'Web Created'), ('imported', 'Imported from XML')], default='web', help_text='Origin of schema (web-created or imported)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schema',
                'verbose_name_plural': 'Schemas',
                'db_table': 'catalog_schema',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemaTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_format', models.CharField(help_text='Target output format (e.g., mp3, wav, mp4)', max_length=50)),
                ('sample_rate', models.IntegerField(blank=True, help_text='Target sample rate in Hz (e.g., 44100, 48000)', null=True)),
                ('bit_depth', models.IntegerField(blank=True, help_text='Target bit depth (e.g., 16, 24)', null=True)),
                ('normalize_db', models.FloatField(blank=True, help_text='Normalization level in dB (e.g., -3.0, -6.0)', null=True)),
                ('schema', models.ForeignKey(help_text='Parent schema', on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='catalog.schema')),
            ],
            options={
                'verbose_name': 'Schema Transformation',
                'verbose_name_plural': 'Schema Transformations',
                'db_table': 'catalog_schema_transformation',
            },
        ),
        migrations.CreateModel(
            name='SchemaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('keyword', 'Keyword Match'), ('extension', 'File Extension'), ('media_type', 'Media Type'), ('attribute', 'File Attribute')], help_text='Type of filtering rule', max_length=20)),
                ('rule_value', models.CharField(help_text='Value to match against', max_length=500)),
                ('logic_operator', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', help_text='Logic operator for combining rules', max_length=3)),
                ('priority', models.IntegerField(default=0, help_text='Rule execution priority (higher = earlier)')),
                ('schema', models.ForeignKey(help_text='Parent schema', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='catalog.schema')),
            ],
            options={
                'verbose_name': 'Schema Rule',
                'verbose_name_plural': 'Schema Rules',
                'db_table': 'catalog_schema_rule',
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='schema',
            index=models.Index(fields=['name'], name='catalog_sch_name_71a641_idx'),
        ),
        migrations.AddIndex(
            model_name='schema',
            index=models.Index(fields=['source_type'], name='catalog_sch_source__71920b_idx'),
        ),
        migrations.AddIndex(
            model_name='schema',
            index=models.Index(fields=['is_active'], name='catalog_sch_is_acti_afd2ef_idx'),
        ),
        migrations.AddField(
            model_name='directorymapping',
            name='schema',
            field=models.ForeignKey(help_text='Parent schema', on_delete=django.db.models.deletion.CASCADE, related_name='directory_mappings', to='catalog.schema'),
        ),
    ]
