# Generated by Django 4.2.7 on 2025-10-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_directorymapping_schema_schematransformation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current processing status for batch operations', max_length=20),
        ),
    ]
