# Generated by Django 4.2.7 on 2025-10-07 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_file_processing_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="directorymapping",
            old_name="is_watched",
            new_name="monitor_enabled",
        ),
    ]
