# Generated by Django 4.2.7 on 2025-10-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Add File-DirectoryMapping relationship for schema-based filtering.

    This migration addresses Story R1.3 (Remediation Backlog) by adding
    a foreign key from File to DirectoryMapping, enabling the queue processor
    to filter files by schema relationship.

    The foreign key is nullable and SET_NULL on delete to handle:
    - Legacy files created before this migration
    - Files that may exist without directory mapping
    - DirectoryMapping deletion without cascading file deletion
    """

    dependencies = [
        ("catalog", "0004_rename_is_watched_to_monitor_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='directory_mapping',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=models.SET_NULL,
                related_name='files',
                to='catalog.directorymapping',
                help_text='Directory mapping (and thus schema) this file is associated with',
            ),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(
                fields=['directory_mapping'],
                name='catalog_fil_directo_idx',
            ),
        ),
    ]
